Removed claim of Python 3 support for now
The model creation code does not support Python 3:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/p264360/git/depccg/build/src/py/lstm_parser_bi.py", line 340, in <module>
    args.func(args)
  File "/home/p264360/git/depccg/build/src/py/lstm_parser_bi.py", line 290, in <lambda>
    if args.mode == "train"
  File "/home/p264360/git/depccg/build/src/py/lstm_parser.py", line 126, in create_traindata
    self._create_samples(trees)
  File "/home/p264360/git/depccg/build/src/py/lstm_parser.py", line 111, in _create_samples
    deps = self._get_dependencies(tree, len(tokens))
  File "/home/p264360/git/depccg/build/src/py/lstm_parser.py", line 95, in _get_dependencies
    assert len(filter(lambda i:i == 0, res)) == 1
TypeError: object of type 'filter' has no len()